### ISSUE TITLE
debug_backtrace add optional parameter 'limit' in php 5.4

### ISSUE THREAD

**Issue by KeNJiKunG** [snapshotpl/ZfSnapEventDebugger#2]
Hellp.

I am encounter with a warning about debuge_backtrace
<code>
Warning: debug_backtrace() expects at most 1 parameter, 2 given in /_-removed-_/vendor/snapshotpl/zf-snap-event-debugger/src/ZfSnapEventDebugger/EventDebuggerListener.php
</code>
The optional parameter 'limit' of function debug_backtrace is added in php 5.4. My php version is 5.3.26.

Thanks.

**Comment by snapshotpl** [comment]
I can fix that tomorrow or you can make na pull request :)

**Comment by snapshotpl** [comment]
Hey @KeNJiKunG . Check version from #3 . You can update your EventDebugger in composer updating to `dev-refactor` version

**Comment by snapshotpl** [comment]
@KeNJiKunG I have just release stable version! Reported issue should be fixed
